### ISSUE TITLE
Cannot kompose up

### ISSUE THREAD

**Issue by Matthieulvt** [kubernetes/kompose#969] opened 2018-03-26 13:35 UTC
Hi, I've been working on some docker project and wanna transform them into a kubernetes cluster. 
```
➜  iotanode_dockerized git:(master) kompose -f docker-compose.yml convert
WARN Unsupported hostname key - ignoring
WARN Volume mount on the host "./volumes/iota/iota.ini" isn't supported - ignoring p
ath on the host
WARN Volume mount on the host "./volumes/iota/ixi" isn't supported - ignoring path on the host
WARN Volume mount on the host "./volumes/iota/mainnetdb" isn't supported - ignoringpath on the host
WARN Volume mount on the host "/etc/localtime" isn't supported - ignoring path on the host
INFO Kubernetes file "iri-node-service.yaml" created
INFO Kubernetes file "iri-node-deployment.yaml" created
INFO Kubernetes file "iri-node-claim0-persistentvolumeclaim.yaml" created
INFO Kubernetes file "iri-node-claim1-persistentvolumeclaim.yaml" created
INFO Kubernetes file "iri-node-claim2-persistentvolumeclaim.yaml" created
INFO Kubernetes file "iri-node-claim3-persistentvolumeclaim.yaml" created
```

The convert went okay but when I try to kompose up, here's what happens: 
```
➜  iotanode_dockerized git:(master) ✗ kompose -f iri-node-deployment.yaml up
ERRO Could not parse config for project iotanodedockerized : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `extensi...` into config.RawService
  line 2: cannot unmarshal !!str `Deployment` into config.RawService
FATA composeObject.Parse() failed, Failed to load compose file: yaml: unmarshal erro
rs:
  line 1: cannot unmarshal !!str `extensi...` into config.RawService
  line 2: cannot unmarshal !!str `Deployment` into config.RawService
➜  iotanode_dockerized git:(master) ✗ kompose up
WARN Unsupported hostname key - ignoring
FATA Error while deploying application: k.Transform failed: image key required withi
n build parameters in order to build and push service 'iri-node'
```

Here's my docker-compose file : 
```
version: '2'

services:
  iri-node: 
    build:
      context: ./iri
      dockerfile: Dockerfile
    container_name: iri-running
    hostname: iota
    volumes: 
      - ./volumes/iota/iota.ini:/iri/iota.ini:ro
      - ./volumes/iota/ixi:/iri/ixi:rw
      - ./volumes/iota/mainnetdb:/iri/mainnetdb:rw
      - /etc/localtime:/etc/localtime:ro
    expose: 
      - "5556"
    ports: 
      - "14600:14600/udp"
      - "15600:15600/tcp"
      - "14265:14265"
```

**Comment by huntal** [comment] 2018-03-26 13:49
Here's how to recreate the bug : 
1) Clone the project here: https://github.com/huntal/iotanode_dockerized
2) `kompose -file docker-compose.yml convert`
3) `kompose up` or kompose -f ... up`

**Comment by cdrage** [comment] 2018-03-26 13:59
@huntal https://github.com/huntal/iotanode_dockerized/blob/master/docker-compose.yml#L1 shows "2.3" for version, have you tried setting it as "2" or even "3"?

**Comment by huntal** [comment] 2018-03-26 14:10
Yes, I've tried, I know that kompose does not support 2.3 version. Tried in version 2.

**Comment by hangyan** [comment] 2018-03-27 04:17
@huntal  Can you try `kompose -f docker-compose.yml up` ?

**Comment by huntal** [comment] 2018-03-27 11:02
Here's the output @hangyan 
```➜  iotanode_dockerized git:(master) ✗ kompose -f docker-compose.yml up
WARN Unsupported hostname key - ignoring
FATA Error while deploying application: k.Transform failed: image key required within build parameters in order to build and push service 'iri-node'```

**Comment by hangyan** [comment] 2018-03-27 13:07
@huntal According to the docker-compose doc, https://docs.docker.com/compose/compose-file/#build, you need to specific the `image` key

**Comment by huntal** [comment] 2018-03-28 09:04
@hangyan thanks for this precision, so i modified my docker-compose file like this : 
```
version: '2'

services:
  iri-node: 
    build:
      context: ./iri
      dockerfile: Dockerfile
    image: iri-node:tag
    container_name: iri-running
    hostname: iota
    volumes: 
      - ./volumes/iota/iota.ini:/iri/iota.ini:ro
      - ./volumes/iota/ixi:/iri/ixi:rw
      - ./volumes/iota/mainnetdb:/iri/mainnetdb:rw
      - /etc/localtime:/etc/localtime:ro
    expose: 
      - "5556"
    ports: 
      - "14600:14600/udp"
      - "15600:15600/tcp"
      - "14265:14265"
```
And when i try again to start `kompose -f docker-compose.yml up`, here's what happening : 
```
➜  iotanode_dockerized git:(master) ✗ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have aDocker ID, head over to https://hub.docker.com to create one.
Username (hystenal): hystenal
Password:
Login Succeeded
➜  iotanode_dockerized git:(master) ✗ kompose -f docker-compose.yml up
WARN Unsupported hostname key - ignoring
INFO Build key detected. Attempting to build and push image 'iri-node:tag'
INFO Building image 'iri-node:tag' from directory 'iri'
INFO Image 'iri-node:tag' from directory 'iri' built successfully
INFO Pushing image 'library/iri-node:tag' to registry 'docker.io'
INFO Multiple authentication credentials detected. Will try each configuration.
INFO Attempting authentication credentials 'https://index.docker.io/v1/
ERRO Unable to push image 'library/iri-node:tag' to registry 'docker.io'. Error: denied
: requested access to the resource is denied
INFO Attempting authentication credentials 'registry.gitlab.com
ERRO Unable to push image 'library/iri-node:tag' to registry 'docker.io'. Error: unauthorized: incorrect username or password
FATA Error while deploying application: k.Transform failed: Unable to push Docker image for service iri-node: unable to push docker image(s). Check that `docker login` workssuccessfully on the command line
```
I am login on the right account btw

**Comment by huntal** [comment] 2018-03-28 09:11
https://github.com/kubernetes/kompose/issues/911
This may be the issue for that i'm checking and closing this issue if it's the case

**Comment by huntal** [comment] 2018-03-28 09:24
So I had some error in my Dockerfile build and fix it to get it correctly working, now i got another error coming from issue 911 so i'm closing this one

**Comment by hangyan** [comment] 2018-03-28 09:25
@huntal Ok, we will keep tracking on that one

**Comment by Sridharc20** [comment] 2018-08-16 11:01
Hi , i'm facing this issue today. Does fix applied to the latest release?

Thanks,

**Comment by YoussefEssa** [comment] 2018-08-27 09:45
Me too guys, I Faced this issue today. Any updates?

**Comment by sinamiandashti** [comment] 2018-08-31 11:43
same here please help

**Comment by marcelofrau** [comment] 2018-09-04 13:06
Putting "image: image-name"on the service to build solves this problem, but I have encountered other problem... 

`  
template-nodejs-backend:
    image: 'template-nodejs-backend'
    build:
        context: '.'
        dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - nodejs-backend-network
    environment:
      MYSQL_HOST: "mysql"
      GET_HOSTS_FROM: dns
    depends_on:
      - 'mysql'
`

The other problem that appears after that is: 
`FATA Error while deploying application: k.Transform failed: Unable to build Docker image for service template-nodejs-backend: Unable to create a tarball: archive/tar: write too long`

Maybe you guys putting just the name on the image solves your problem. I am still trying to figure it out how to solve the next poblem, if you guys know anything please let me know..

**Comment by YoussefEssa** [comment] 2018-09-05 06:57
The below command works with me 
`kompose up --provider=openshift --build="build-config" -v --file docker-compose-CeleryExecutor.yml`
and this error appeared
`FATA Error while deploying application: Get https://openshift-.com:443/api: x509: certificate signed by unknown authority`

**Comment by notlose** [comment] 2019-06-04 07:22
> Unable to create a tarball: archive/tar: write too long

same problem, Unable to create a tarball: archive/tar: write too long
did you found a solution?

**Comment by aylesm** [comment] 2019-07-24 15:44
Same here.

**Comment by alechp** [comment] 2019-12-31 19:24
For anyone else struggling, hopefully this helps:

## Errors
**image key**
![Screen Shot 2019-12-31 at 11 05 39 AM](https://user-images.githubusercontent.com/3058939/71631718-0d4b2d80-2bbf-11ea-90a1-d90e2d65c38f.png)

**write too long**
![Screen Shot 2019-12-31 at 11 05 39 AM](https://user-images.githubusercontent.com/3058939/71631822-aaa66180-2bbf-11ea-8aae-be17751d8799.png)


## What worked for me
**changes made to address `image key required` and `write too long` errors**
![Screen Shot 2019-12-31 at 11 19 16 AM](https://user-images.githubusercontent.com/3058939/71631808-89de0c00-2bbf-11ea-8a55-1890f4ab58f5.png)

* Image key error was solved by adding the image key
* Tarball issue was solved by removing context

**Comment by hangyan** [comment] 2020-01-01 03:49
That's odd, i have test this compose file and it did not report this `tar: write too long` error..

**Comment by gonzabt3** [comment] 2020-06-15 05:08
the problem is the symboliks links,find with
`ls -laR . | grep -B 5 " -> "`
and removes that,i remove node_modules and vendor folders and it is works

**Comment by kiransmartclean** [comment] 2020-08-26 18:25
> The below command works with me
> `kompose up --provider=openshift --build="build-config" -v --file docker-compose-CeleryExecutor.yml`
> and this error appeared
> `FATA Error while deploying application: Get https://openshift-.com:443/api: x509: certificate signed by unknown authority`

@YoussefEssa, same issue. Could you able to solve it?

**Comment by ComradePashka** [comment] 2021-11-25 05:21
Hi guys, just install kompose today following instructions from: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/ and it said: `unknown command "up" for "kompose"` so then I run `kompose version` and it's 1.24.0 (4a2a0458) however latest one is v1.26.0. I repeat installation steps and get same results, seems that kompose don't know up|down commands at all:
```
root@host:/home/user/project# kompose
Kompose is a tool to help users who are familiar with docker-compose move to Kubernetes.

Usage:
  kompose [command]

Available Commands:
  completion  Output shell completion code
  convert     Convert a Docker Compose file
  help        Help about any command
  version     Print the version of Kompose

Flags:
      --error-on-warning    Treat any warning as an error
  -f, --file stringArray    Specify an alternative compose file
  -h, --help                help for kompose
      --provider string     Specify a provider. Kubernetes or OpenShift. (default "kubernetes")
      --suppress-warnings   Suppress all warnings
  -v, --verbose             verbose output

Use "kompose [command] --help" for more information about a command.
```

**Comment by hangyan** [comment] 2021-11-29 02:16
@ComradePashka Kompose has removed up/down comand. You can use `| kubectl apply -f` to create the resources in your cluster, it's eaier and more stable

**Comment by ComradePashka** [comment] 2021-11-29 03:19
@hangyan yeah, I got it, I mentioned about it in documentation repo, they labeled something to fix it, to not confuse people, like me :-)

**Comment by hangyan** [comment] 2021-11-30 05:35
I'm not sure what docuement you are refering to? can you share me a link?

**Comment by ComradePashka** [comment] 2021-11-30 09:54
@hangyan yep, I mentioned it in my first message, there are still sections about `up`/`down` subcommands: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/#kompose-up

**Comment by hangyan** [comment] 2021-11-30 15:20
https://github.com/kubernetes/website/pull/30690

**Closed** 2022-04-29 16:40 UTC
Labels: lifecycle/rotten
