### ISSUE TITLE
Group files into one?

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1582] opened 2023-02-09 02:09 UTC
### What would you like to be added?

I'm curious why this entire time we create multiple files for deployment? And why not one file with all the containers under the `containers` array?

For example:

```yaml
        containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.4.0
          args:
            - -ssh
            - -repo=git@github.com:foobar/wiki
            - -branch=master
            - -dest=git-sync
            - -add-user
          securityContext:
            runAsUser: 65533
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: markdown
              mountPath: /tmp/git
        - name: hugo
          image: foobar/hugo
          imagePullPolicy: Always
          volumeMounts:
          - name: markdown
            mountPath: /src
          - name: html
            mountPath: /dest
          env:
          - name: HUGO_SRC
            value: /src/git-sync
          - name: HUGO_BUILD_DRAFT
            value: "true"
          - name: HUGO_BASE_URL
            value: foobar.com
```

Why aren't we grouping the containers in one deployment?

```sh
▶ kompose convert -f docker-compose.yaml
INFO Kubernetes file "frontend-tcp-service.yaml" created
INFO Kubernetes file "redis-master-service.yaml" created
INFO Kubernetes file "redis-slave-service.yaml" created
INFO Kubernetes file "frontend-deployment.yaml" created
INFO Kubernetes file "redis-master-deployment.yaml" created
INFO Kubernetes file "redis-slave-deployment.yaml" created
```

When in reality.. most users just have one file for deployment and all the containers, etc.

So odd how all this time we've been splitting them into multiple files? Looking back into the history I can't find anything.

### Why is this needed?

Organizing. 

Being able to provide just three files would be awesome, so instead it'll just be three files of:

- deployment.yaml
- volumes.yaml
- services.yaml

etc. etc.

**Comment by cdrage** [comment] 2023-02-09 02:09
What do you think @AhmedGrati

**Comment by AhmedGrati** [comment] 2023-02-09 07:35
I think it's a duplicate of #1539.

**Comment by cdrage** [comment] 2023-02-09 13:27
Ah, no. #1539 groups them by adding them to one file and separating them with `---`

This issue talks about making it under `containers:` in the file. For example:


```yaml
        containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.4.0
          args:
            - -ssh
            - -repo=git@github.com:cdrage/wiki
            - -branch=master
            - -dest=git-sync
            - -add-user
          securityContext:
            runAsUser: 65533
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: markdown
              mountPath: /tmp/git
        - name: hugo
          image: cdrage/hugo
          imagePullPolicy: Always
          volumeMounts:
          - name: markdown
            mountPath: /src
          - name: html
            mountPath: /dest
          env:
          - name: HUGO_SRC
            value: /src/git-sync
          - name: HUGO_BUILD_DRAFT
            value: "true"
          - name: HUGO_BASE_URL
            value: foobar.com
 ```

**Comment by AhmedGrati** [comment] 2023-02-09 13:45
Ah okay makes sens!

**Comment by AhmedGrati** [comment] 2023-02-09 20:25
@cdrage I think we should give users the flexibility to group whatever containers they want, by using some labels to group containers in the same Deployment/DaemonSets. 
I'd propose that the default behavior is deploying each container alone, and I think it's a best practice in k8s to decouple containers in separate pods. WDYT?

**Comment by cdrage** [comment] 2023-02-09 21:17
> @cdrage I think we should give users the flexibility to group whatever containers they want, by using some labels to group containers in the same Deployment/DaemonSets. I'd propose that the default behavior is deploying each container alone, and I think it's a best practice in k8s to decouple containers in separate pods. WDYT?

Agreed, I think we should add the option to the group mode to be able to group all containers in the docker-compose yaml into one deployment, otherwise, it's still find to have it in separate deployments.

Like... --group-mode=containers or something similar to how we do it right now with volumes.

**Comment by cdrage** [comment] 2023-02-10 15:52
NVM I'm an idiot, we already have this implemented: https://github.com/kubernetes/kompose/pull/1394

The problem is that there isn't that great of documentation outlining the actual feature.

**Closed** 2023-02-10 15:53 UTC
Labels: kind/feature
