### ISSUE TITLE
Add Support for docker-compose 3.4

### ISSUE THREAD

**Issue by kitingChris** [kubernetes/kompose#1125] opened 2019-04-29 07:06 UTC
```
$ kompose convert -f docker-compose.yml 
FATA Version 3.4 of Docker Compose is not supported. Please use version 1, 2 or 3
```
Is support for 3.4 already in sight?

**Comment by PureKrome** [comment] 2019-05-03 02:58
Same here for version `3.5` :( sadness

**Comment by hangyan** [comment] 2019-05-03 03:36
It should not be. I have check the latest code , we have support 3.4/3.5 now. Which versions of kompose you guys use?

**Comment by PureKrome** [comment] 2019-05-03 03:43
just downloaded the latest version, now. 

```
PS C:\> c:\temp\kompose version
1.17.0 (a74acad)
PS C:\>
```

**Comment by hangyan** [comment] 2019-05-03 03:46
@PureKrome Sorry about that, i think the support is only is the master branch and not release yet..

**Comment by PureKrome** [comment] 2019-05-03 03:47
yep. confirmed @hangyan 

```
PS C:\> c:\temp\kompose version
1.18.0 (06a2e56)
PS C:\projects\personal\hornet\Hornet.Backend> C:\temp\kompose.exe convert -f .\docker-compose.yml
[31mFATA[0m Version 3.5 of Docker Compose is not supported. Please use version 1, 2 or 3
PS C:\projects\personal\hornet\Hornet.Backend>
```

**Comment by PureKrome** [comment] 2019-05-10 02:47
@hangyan so has this been released/working yet? what version is this / will this be in?

**Comment by hangyan** [comment] 2019-05-10 02:49
Well i'm not in charge of the release, but usually there will be a monthly release. It's merged in master already, you can check it out

**Comment by Quinncuatro** [comment] 2019-07-25 01:31
Are there directions on how to download the source, build, and use the latest versions while we're waiting for an "official" release of v1.18?

**Comment by PureKrome** [comment] 2019-07-25 01:34
and also .. can we get a release soon? 

99% of people don't want to / can't / or know how to (as @Quinncuatro has said, above) build latest.

**Comment by Quinncuatro** [comment] 2019-07-25 01:36
Yeah. I don't want to sound like an ungrateful asshole, because this seems really cool.

But this should be keeping better pace with docker-compose's release cadence, especially considering it's owned by the K8s GitHub org.

**Closed** 2019-12-22 03:22 UTC
Labels: lifecycle/rotten
