### ISSUE TITLE
question: how does converting service discovery by hostname with docker-compose work?

### ISSUE THREAD

**Issue by longility** [kubernetes/kompose#1154] opened 2019-07-08 13:25 UTC
I'm new to k8s and kompose. If I'm in the wrong place to ask this question, please direct me.

I have two services, A and B. A is making a http api call to B using the hostname like so `http://B/api/service-info`. I deployed using the generated ymls from `kompose`, but I'm not familiar enough to know what I am missing to have the service discovery work in k8s.

Some more context..since B is an internal service (no external port), kompose did not create a service yml. 

Any thoughts?

**Comment by hangyan** [comment] 2019-07-08 15:40
What is a non-public service? Does compose have this concept?

**Comment by longility** [comment] 2019-07-08 15:54
@hangyan I updated my wording to hopefully make more since. What I meant by non-public service is that the service is internal and cannot be accessed externally, only within the network. So for compose, to make a service externally accessible, we would provide [ports](https://docs.docker.com/compose/compose-file/#ports) to map from host to container port. Sorry for the confusion.

**Comment by hangyan** [comment] 2019-07-09 14:36
@longility Is this caused by #1095? I will look into the code and see how to fix this ,may be there is a workaround, but it need some time to be merged in

**Comment by longility** [comment] 2019-07-09 14:47
My gut says yes.

I think once the issue #1095 is fixed, I can verify if that fixes this or there may be additional steps.

**Comment by hangyan** [comment] 2019-07-09 15:28
The current code seems ignore the `expose` key and support the `ports` key. It will take some time to fix this and choose a good map to kubernetes resources.

**Comment by hangyan** [comment] 2019-07-09 15:29
I think the `expose` and `ports` can both map to normal kubernetes services

**Comment by longility** [comment] 2019-07-09 15:51
When I have time, I can play around with manually creating the service yml to see if it does what I think it should.

Also, I wonder if the `expose` key was ignored for a particular reason or was it just overlooked.

**Comment by longility** [comment] 2019-07-12 12:05
I was able to manually create the service yaml and get my microservices communicating to each other. So the issue #1095 should fix and get my scenario working, which is to resolve based on hostnames.

**Closed** 2019-12-09 14:30 UTC
Labels: kind/feature, lifecycle/rotten
