### ISSUE TITLE
Upgrade Kubernetes module to the latest version `v0.27.3`

### ISSUE THREAD

**Issue by payamQorbanpour** [kubernetes/kompose#1676] opened 2023-07-18 14:33 UTC
### Expected Behavior

No error

### Actual Behavior

/go/pkg/mod/github.com/kubernetes/kompose@v1.29.0/pkg/transformer/kubernetes/podspec.go:285:9: probe.Handler undefined (type "k8s.io/api/core/v1".Probe has no field or method Handler)
/go/pkg/mod/github.com/kubernetes/kompose@v1.29.0/pkg/transformer/kubernetes/podspec.go:285:23: undefined: api.Handler
/go/pkg/mod/github.com/kubernetes/kompose@v1.29.0/pkg/transformer/kubernetes/podspec.go:291:9: probe.Handler undefined (type "k8s.io/api/core/v1".Probe has no field or method Handler)
/go/pkg/mod/github.com/kubernetes/kompose@v1.29.0/pkg/transformer/kubernetes/podspec.go:291:23: undefined: api.Handler
/go/pkg/mod/github.com/kubernetes/kompose@v1.29.0/pkg/transformer/kubernetes/podspec.go:298:9: probe.Handler undefined (type "k8s.io/api/core/v1".Probe has no field or method Handler)
/go/pkg/mod/github.com/kubernetes/kompose@v1.29.0/pkg/transformer/kubernetes/podspec.go:298:23: undefined: api.Handler

### Steps To Reproduce

1. in your code import the package like bellow:
```
import (
	"github.com/kubernetes/kompose/pkg/kobject"
	"github.com/kubernetes/kompose/pkg/loader/compose"
	"github.com/kubernetes/kompose/pkg/transformer/kubernetes"
)
```
2. try to build application:
`go build`

### Kompose Version

```Text
v1.30.0
```

### Anything else?

Hey, Im trying to use kubernetes/kompose package in my Golang application but i'm facing the above error. Any idea about the root cause and how to deal with it?

**Comment by AhmedGrati** [comment] 2023-07-18 15:19
Hey @payamQorbanpour Thanks for opening the issue.
Actually, with the following code, I couldn't reproduce the error:
```go
package main

import (
	"fmt"

	"github.com/kubernetes/kompose/pkg/kobject"
	"github.com/kubernetes/kompose/pkg/loader/compose"
	"github.com/kubernetes/kompose/pkg/transformer/kubernetes"
)

func main() {
	a := kobject.KomposeObject{}
	fmt.Println(a)
	b := compose.Compose{}
	fmt.Println(b)
	c := kubernetes.Kubernetes{}
	fmt.Println(c)
}
```
Can you provide me with the code that you used to reproduce the issue?
Other than that, we are actually on our way to release the client for Kompose, so you won't need anymore to use these packages. Look at #1593.

**Comment by payamQorbanpour** [comment] 2023-07-18 16:01
Thanks for reaching out. Bellow is my sample code:
Also, when I use version `k8s.io/api v0.27.0`, I encounter the error. However, when I use version `k8s.io/api v0.22.5`, everything works fine.

```
package main

import (
	"fmt"

	"github.com/kubernetes/kompose/pkg/kobject"
	"github.com/kubernetes/kompose/pkg/loader/compose"
	"github.com/kubernetes/kompose/pkg/transformer/kubernetes"
)

func main() {
	// Load a Docker Compose file
	loader := compose.Compose{}
	object, err := loader.LoadFile([]string{"docker-compose.yaml"})
	if err != nil {
		panic(err)
	}

	// Convert to Kubernetes objects
	transformer := kubernetes.Kubernetes{}
	objects, err := transformer.Transform(object, kobject.ConvertOptions{})
	if err != nil {
		panic(err)
	}

	fmt.Println(objects)
}

```

**Comment by AhmedGrati** [comment] 2023-07-19 11:12
@payamQorbanpour After investigating this issue, I found that the problem is that in Kompose we are internally using the `k8s.io/api` package with version `0.22.5`. https://github.com/kubernetes/kompose/blob/317ba2922eccf1924131a0115a6555bbc07b4f44/go.mod#L23-L24
Upgrading this package to the latest version in Kompose should be a good option. If you want you can open a PR. Let me know if you want me to assign this issue for you
/good-first-issue

**Comment by payamQorbanpour** [comment] 2023-07-19 11:31
> @payamQorbanpour After investigating this issue, I found that the problem is that in Kompose we are internally using the `k8s.io/api` package with version `0.22.5`.
> 
> https://github.com/kubernetes/kompose/blob/317ba2922eccf1924131a0115a6555bbc07b4f44/go.mod#L23-L24
> 
> 
> Upgrading this package to the latest version in Kompose should be a good option. If you want you can open a PR. Let me know if you want me to assign this issue for you
> /good-first-issue

Yes, I'd be honored to work on this project. I would also be pleased to help you with implementing the client #1593 you mentioned.

**Comment by AhmedGrati** [comment] 2023-07-19 11:40
/assign payamQorbanpour

For the #1593, unfortunately, it's finished and It only needs a rebase to be ready. But I will let you know if it needs other improvements.

**Closed** 2023-07-19 16:23 UTC
Labels: help wanted, kind/bug, good first issue
